### ISSUE TITLE
Caption separated from `\textfig` and `\widefig`

### ISSUE THREAD

**Issue by artperrin** [sylvain-kern/tufte-style-article#1]
Hi Sylvain,
I observed a weird behavious with this _great_ `tufte-style-article` class: sometimes the caption of a `\widefig` or `\textfig` is separated from the figure. Here are one example of each :
* when displaying a `\widefig` on a given page, its caption shows up on the next page, despite having presumably enough space for being written directly below the picture.
![issue_1](https://user-images.githubusercontent.com/78485334/125303784-57bd7680-e32d-11eb-8167-f8a5b73533ec.PNG)
Corresponding code :
```tex
\documentclass[
    colorful,
]{tufte-style-article}

\usepackage{lipsum}

\begin{document}
    
    \section{First some filler text, on the second page a picture, and on the third the picture's caption}

    \lipsum[1-5]

    \widefig[.9]{treboul.jpg}{The infamous Treboul island}{treboul}

    The third page.

\end{document}
```
* also when displaying a `\textfig` on an already filled page (having just a little space left), the picture shows up on the next page while its caption is still written on the previous (using the small space).
![issue_2](https://user-images.githubusercontent.com/78485334/125303776-55f3b300-e32d-11eb-8542-8326688473f1.PNG)
Corresponding code :
```tex
\documentclass[
    colorful,
]{tufte-style-article}

\usepackage{lipsum}

\begin{document}
    
    \section{First some filler text and the picture's caption, on the second page the picture}

    \lipsum[1-5]

    \textfig[.9]{treboul.jpg}{The infamous Treboul island}{treboul}

    The second page.

\end{document}
```
For the sake of testing, you can find the picture [here](https://fr.wikipedia.org/wiki/Tr%C3%A9boul_(Finist%C3%A8re)#/media/Fichier:Tr%C3%A9boul_from_Tristan_Island.JPG).

I tried to tweak a `bmargin` parameter (from `40pt` to `100pt`) in the `regular` geometry defined within your class file, without any success: this behaviour still appears.
I hope you can fix this small issue for me and the other users to keep on writting nice tufte-stylized articles ! 👍

**Comment by sylvain-kern** [comment]
Hi dear Arthur, and thank you for pointing this issue.

I think this is actually a pretty big issue (maybe the biggest flaw of the whole class). Actually I would like to clean up all the figure macros so that they are LaTeX floats (now they are just `\includegraphics` with some surrounding decoration).

I will let you know once I have completed this herculean task.

**Comment by artperrin** [comment]
Alright, I'm looking forward to seeing those figures as floats ! Thanks for your answer.

**Comment by sylvain-kern** [comment]
My dear Arthur, 

Just commited the fixes !
Your issue had me work quite a bit on the floating environments. Until now they were pretty terrible but now all of these work with the `sidenotes` package. They now float like native figures and caption don't separate from images anymore.

Thanks again for your patience and interest for this project,
20sil
